### ISSUE TITLE
release failed in the CI

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#1117]
### What

Running the release with the CI failed, though, the tag was created along the commit with the update of versioning.

### Stacktrace

```
[2021-05-17T10:32:11.593Z] [INFO] [INFO] --- maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) @ jenkins-library ---
[2021-05-17T10:32:11.593Z] [INFO] [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[2021-05-17T10:32:11.593Z] [INFO] [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar (262 kB at 793 kB/s)
[2021-05-17T10:32:11.593Z] [INFO] [INFO] Skipping artifact deployment
[2021-05-17T10:32:11.593Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] [INFO] [INFO] BUILD SUCCESS
[2021-05-17T10:32:11.593Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] [INFO] [INFO] Total time:  9.082 s
[2021-05-17T10:32:11.593Z] [INFO] [INFO] Finished at: 2021-05-17T10:32:11Z
[2021-05-17T10:32:11.593Z] [INFO] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] [INFO] Cleaning up after release...
[2021-05-17T10:32:11.593Z] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] [INFO] BUILD SUCCESS
[2021-05-17T10:32:11.593Z] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] [INFO] Total time:  34.068 s
[2021-05-17T10:32:11.593Z] [INFO] Finished at: 2021-05-17T10:32:11Z
[2021-05-17T10:32:11.593Z] [INFO] ------------------------------------------------------------------------
[2021-05-17T10:32:11.593Z] java.lang.NullPointerException
[2021-05-17T10:32:11.593Z] 	at org.fusesource.jansi.AnsiPrintStream.uninstall(AnsiPrintStream.java:79)
[2021-05-17T10:32:11.593Z] 	at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:524)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.shared.utils.logging.MessageUtils.doSystemUninstall(MessageUtils.java:101)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.shared.utils.logging.MessageUtils.systemUninstall(MessageUtils.java:80)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:203)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-17T10:32:11.593Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-17T10:32:11.593Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[2021-05-17T10:32:11.593Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[2021-05-17T10:32:11.593Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[2021-05-17T10:32:11.593Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-17T10:32:11.593Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-17T10:32:11.593Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[2021-05-17T10:32:11.593Z] 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:60)

```

### Works locally

```bash
➜  apm-pipeline-library git:(master) ./mvnw release:prepare release:perform -V --batch-mode '-Darguments=-DskipTests=true --batch-mode' 
```

caused

```bash
...
[INFO] [INFO] Installing /Users/vmartinez/work/src/github.com/elastic/apm-pipeline-library/target/checkout/pom.xml to /Users/vmartinez/.m2/repository/co/elastic/jenkins-library/1.1.217/jenkins-library-1.1.217.pom
[INFO] [INFO] 
[INFO] [INFO] --- maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) @ jenkins-library ---
[INFO] [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[INFO] [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar (0 B at 0 B/s)
[INFO] [INFO] Skipping artifact deployment
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD SUCCESS
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  12.990 s
[INFO] [INFO] Finished at: 2021-05-17T12:18:25+01:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] Cleaning up after release...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.326 s
[INFO] Finished at: 2021-05-17T12:18:25+01:00
[INFO] ------------------------------------------------------------------------
➜  apm-pipeline-library git:(master) echo $?
0
```

**Comment by v1v** [comment]
Though the maven version that I used locally differs from the one in the CI:

```
### CI
12:45:36  + ./mvnw clean install -V --batch-mode -DskipTests
12:45:36  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
12:45:36  Apache Maven 4.0.0-alpha-1-SNAPSHOT (3fabb639a31d6076b1649c1a08828febabddf44a)
```

Locally:

```
Apache Maven 4.0.0-alpha-1-SNAPSHOT (b08e4d277e02abe9455e6c05e8fc6ae2b12a68fe)
Maven home: /Users/vmartinez/.m2/wrapper/dists/apache-maven-4.0.0-alpha-1-SNAPSHOT-bin/s0m0e7mg6h9hr8umuisf0sdq9/apache-maven
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /Users/vmartinez/.sdkman/candidates/java/8.0.282.j9-adpt/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```
