### ISSUE TITLE
generateBuildReport: net.sf.json.JSONNull.contains()  

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#1616]
```
15:31:43  ERROR: generateBuildReport: Error generating build report
15:31:43  groovy.lang.MissingMethodException: No signature of method: net.sf.json.JSONNull.contains() is applicable for argument types: (java.lang.String) values: [githubPrCheckApproved]
15:31:43  Possible solutions: toString(), toString(), toString(), notify(), toString(int)
15:31:43  	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.find(CpsDefaultGroovyMethods.java:1315)
15:31:43  Caused: groovy.text.TemplateExecutionException: Template execution error at line 77:
15:31:43          76: <% errorGitHub = stepsErrors?.find{it?.result == "FAILURE" && it?.displayName?.contains('Notifies GitHub')}%>
15:31:43      --> 77: <% errorGithubPrCheckApproved = stepsErrors?.find{it?.result == "FAILURE" && it?.displayDescription?.contains('githubPrCheckApproved')}%>
15:31:43          78: <% errorDeleteDir = stepsErrors?.find{it?.result == "FAILURE" && it?.displayName?.contains('Recursively delete the current directory from the workspace')}%>
15:31:43  
```

**Comment by v1v** [comment]
Then https://github.com/elastic/apm-server/pull/7613#issuecomment-1075034973 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/2871786/159533181-b14900e3-e3a3-4fdb-9740-bc43757dc31a.png">

**Comment by v1v** [comment]
```
09:59:29  groovy.lang.MissingMethodException: No signature of method: net.sf.json.JSONNull.contains() is applicable for argument types: (java.lang.String) values: [githubPrCheckApproved]
09:59:29  Possible solutions: toString(), toString(), toString(), notify(), toString(int)
09:59:29  	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.findAll(CpsDefaultGroovyMethods.java:1068)
09:59:29  Caused: groovy.text.TemplateExecutionException: Template execution error at line 82:
09:59:29          81:                                       !it?.displayName?.contains('Archive JUnit') &&
09:59:29      --> 82:                                       !it?.displayDescription?.contains('githubPrCheckApproved') &&
09:59:29          83:                                       !it?.displayDescription?.contains('approval-list/elastic') &&
09:59:29  
```
