### ISSUE TITLE
pre-commit step uses an old fashion way to install the pre-commit

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#1683]
https://github.com/elastic/apm-pipeline-library/blob/7a739f20181aba1b7b09e66c022b5fe03325f5bf/vars/preCommit.groovy#L51-L57 therefore if we use python-3.10 then it does not work as stated in https://github.com/elastic/apm-agent-python/pull/1542#discussion_r864807779

Let's keep this issue open until we manage to support the new installation

Thanks @beniwohli

**Comment by kuisathaverat** [comment]
On our Ubuntu 22.04 workers fail with the following error

```
[2022-07-05T14:02:54.559Z] + PYTHON_COMMAND=python
[2022-07-05T14:02:54.559Z] + command -v python3
[2022-07-05T14:02:54.559Z] /bin/python3
[2022-07-05T14:02:54.559Z] + PYTHON_COMMAND=python3
[2022-07-05T14:02:54.560Z] + python3 -
[2022-07-05T14:02:54.560Z] + curl -s https://pre-commit.com/install-local.py
[2022-07-05T14:02:55.865Z] Using base prefix '/usr'
[2022-07-05T14:02:55.865Z] New python executable in /var/lib/jenkins/workspace/st-env_oblt-test-env-mbp_PR-2370/.pre-commit-venv/bin/python3
[2022-07-05T14:02:55.865Z] Also creating executable in /var/lib/jenkins/workspace/st-env_oblt-test-env-mbp_PR-2370/.pre-commit-venv/bin/python
[2022-07-05T14:02:55.865Z] Traceback (most recent call last):
[2022-07-05T14:02:55.865Z]   File "/tmp/.virtualenv-pkg/virtualenv.py", line 2633, in <module>
[2022-07-05T14:02:55.865Z]     main()
[2022-07-05T14:02:55.865Z]   File "/tmp/.virtualenv-pkg/virtualenv.py", line 859, in main
[2022-07-05T14:02:55.865Z]     create_environment(
[2022-07-05T14:02:55.865Z]   File "/tmp/.virtualenv-pkg/virtualenv.py", line 1161, in create_environment
[2022-07-05T14:02:55.865Z]     install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
[2022-07-05T14:02:55.866Z]   File "/tmp/.virtualenv-pkg/virtualenv.py", line 1720, in install_python
[2022-07-05T14:02:55.866Z]     fix_local_scheme(home_dir, symlink)
[2022-07-05T14:02:55.866Z]   File "/tmp/.virtualenv-pkg/virtualenv.py", line 1806, in fix_local_scheme
[2022-07-05T14:02:55.866Z]     if sysconfig._get_default_scheme() == "posix_local":
[2022-07-05T14:02:55.866Z] AttributeError: module 'sysconfig' has no attribute '_get_default_scheme'. Did you mean: 'get_default_scheme'?
[2022-07-05T14:02:55.866Z] Downloading https://files.pythonhosted.org/packages/a4/e3/1f067de470e3a86875ed915438dc3bd781fb0346254f541190a09472b677/virtualenv-16.7.10.tar.gz
[2022-07-05T14:02:55.866Z] Done.
```
