### ISSUE TITLE
`pytest-otel` seems to be broken on Python >= 3.10.0

### ISSUE THREAD

**Issue by belimawr** [elastic/apm-pipeline-library#1687]
OS: Linux (Arch Linux)
Python: 3.10.4

Since Python 3.10.0, whenever I run the Python tests on [Beats](https://github.com/elastic/beats), more specifically Filebeat, I get this error (all tests fail):
```
Traceback (most recent call last):
  File "/home/vagrant/beats/build/ve/linux/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/_pytest/main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pytest_otel/__init__.py", line 266, in pytest_sessionfinish
    end_span(session_name, exitCodeToOutcome(exitstatus))
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/pytest_otel/__init__.py", line 163, in end_span
    spans[span_name].end()
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 853, in end
    self._span_processor.on_end(self._readable_span())
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 158, in on_end
    sp.on_end(span)
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 90, in on_end
    token = attach(set_value(_SUPPRESS_INSTRUMENTATION_KEY, True))
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 116, in set_value
    context = get_current()
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 67, in wrapper
    return func(*args, **kwargs)  # type: ignore[misc]
  File "/home/vagrant/beats/build/ve/linux/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 131, in get_current
    return _RUNTIME_CONTEXT.get_current()  # type:ignore
AttributeError: 'NoneType' object has no attribute 'get_current'
```

Removing `pytest-otel` solves the problem in the sense the tests can run, but I am not sure about what happens with the instrumentation.

So far I've tested it with Python (using `pyenv`):
* 3.8.13
* 3.9.12
* 3.10.0
* 3.10.4

Unfortunately I have not had time to create a small example to reproduce it.

**Comment by kuisathaverat** [comment]
It seems related to OpenTelemetry https://github.com/open-telemetry/opentelemetry-python/issues/2288 I will update the OpenTelemetry SDK and test if it is resolved.

**Comment by kuisathaverat** [comment]
you are testing it locally, isn't it? because I do not see errors on any of the CIs we have, IIRC we do not have any with Python 3.10 yet

**Comment by belimawr** [comment]
Yes, it's not affecting CI.

**Comment by kuisathaverat** [comment]
it is already fixed but not released https://github.com/elastic/apm-pipeline-library/pull/1664

**Comment by kuisathaverat** [comment]
the release 1.1.0 contains the fix
