### ISSUE TITLE
GitHub build comment failed

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#1744]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/2871786/175258810-878da781-d1d9-4034-932a-e673b797898a.png">

https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-2688/1/pipeline/19094

```
[2022-06-23T07:04:47.882Z] ERROR: generateBuildReport: Error generating build report
[2022-06-23T07:04:47.883Z] groovy.lang.MissingMethodException: No signature of method: net.sf.json.JSONNull.contains() is applicable for argument types: (java.lang.String) values: [githubPrCheckApproved]
[2022-06-23T07:04:47.883Z] Possible solutions: toString(), toString(), toString(), notify(), toString(int)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.findAll(CpsDefaultGroovyMethods.java:1068)
[2022-06-23T07:04:47.883Z] Caused: groovy.text.TemplateExecutionException: Template execution error at line 82:
[2022-06-23T07:04:47.883Z]         81:                                       !it?.displayName?.contains('Archive JUnit') &&
[2022-06-23T07:04:47.883Z]     --> 82:                                       !it?.displayDescription?.contains('githubPrCheckApproved') &&
[2022-06-23T07:04:47.883Z]         83:                                       !it?.displayDescription?.contains('approval-list/elastic') &&
[2022-06-23T07:04:47.883Z] 
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2022-06-23T07:04:47.883Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
[2022-06-23T07:04:47.883Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2022-06-23T07:04:47.883Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2022-06-23T07:04:47.883Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2022-06-23T07:04:47.883Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2022-06-23T07:04:48.012Z] [Pipeline] // catchError
[2022-06-23T07:04:48.029Z] [Pipeline] }
[2022-06-23T07:04:48.134Z] [Pipeline] // catchError
[2022-06-23T07:04:48.180Z] [Pipeline] catchError
[2022-06-23T07:04:48.184Z] [Pipeline] {
[2022-06-23T07:04:48.271Z] [Pipeline] catchError
[2022-06-23T07:04:48.275Z] [Pipeline] {
[2022-06-23T07:04:48.351Z] [Pipeline] libraryResource
[2022-06-23T07:04:48.462Z] [Pipeline] }
[2022-06-23T07:04:48.469Z] ERROR: generateBuildReport: Error generating build report
[2022-06-23T07:04:48.470Z] groovy.lang.MissingMethodException: No signature of method: net.sf.json.JSONNull.contains() is applicable for argument types: (java.lang.String) values: [githubPrCheckApproved]
[2022-06-23T07:04:48.470Z] Possible solutions: toString(), toString(), toString(), notify(), toString(int)
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.findAll(CpsDefaultGroovyMethods.java:1068)
[2022-06-23T07:04:48.470Z] Caused: groovy.text.TemplateExecutionException: Template execution error at line 82:
[2022-06-23T07:04:48.470Z]         81:                                       !it?.displayName?.contains('Archive JUnit') &&
[2022-06-23T07:04:48.470Z]     --> 82:                                       !it?.displayDescription?.contains('githubPrCheckApproved') &&
[2022-06-23T07:04:48.470Z]         83:                                       !it?.displayDescription?.contains('approval-list/elastic') &&
[2022-06-23T07:04:48.470Z] 
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
[2022-06-23T07:04:48.470Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2022-06-23T07:04:48.471Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2022-06-23T07:04:48.471Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2022-06-23T07:04:48.471Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2022-06-23T07:04:48.471Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2022-06-23T07:04:48.471Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
[2022-06-23T07:04:48.471Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2022-06-23T07:04:48.471Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2022-06-23T07:04:48.471Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2022-06-23T07:04:48.471Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
```

**Comment by v1v** [comment]
Duplicates https://github.com/elastic/apm-pipeline-library/issues/1616 ?
