### ISSUE TITLE
Regression with the refactoring in #926

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#930]
### What 

No more digested build comments! :(

### Why

```
12:23:04  ERROR: There were some failures when notifying results in the PR
12:23:04  java.lang.NullPointerException: Cannot invoke method trim() on null object
12:23:04  	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
12:23:04  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
12:23:04  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
12:23:04  	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
12:23:04  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
12:23:04  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
12:23:04  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
12:23:04  	at co.elastic.NotificationManager.notifyPR(NotificationManager.groovy:227)
12:23:04  	at notifyBuildResult.createGitHubComment(notifyBuildResult.groovy:211)
```

**Comment by v1v** [comment]
Solved now
https://github.com/elastic/apm-pipeline-library/pull/932#issuecomment-768386348
