### ISSUE TITLE
getStageId failed when using some parallel steps

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#961]
### What

elastic/beats.git builds are failing with some unexpected recursion:

```15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  Also:   java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  java.lang.StackOverflowError: Excessively nested closures/functions at log.call(log.groovy:30) - look for unbounded recursion - call depth: 1025
15:29:03  	at com.cloudbees.groovy.cps.impl.CpsFunction.invoke(CpsFunction.java:28)
15:29:03  	at com.cloudbees.groovy.cps.impl.CpsCallableInvocation.invoke(CpsCallableInvocation.java:57)
15:29:03  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:98)
15:29:03  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
15:29:03  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
15:29:03  	at sun.reflect.GeneratedMethodAccessor501.invoke(Unknown Source)
15:29:03  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:29:03  	at java.lang.reflect.Method.invoke(Method.java:498)
15:29:03  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
15:29:03  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
15:29:03  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
15:29:03  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
15:29:03  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
15:29:03  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
15:29:03  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
15:29:03  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
15:29:03  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
15:29:03  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:29:03  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
15:29:03  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
15:29:03  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
15:29:03  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15:29:03  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:29:03  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:29:03  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:29:03  	at java.lang.Thread.run(Thread.java:748)
15:29:03  Finished: FAILURE
```

We have been using it without any issues in the apm-pipeline-library for a few days, so maybe the parallel step could be the reason for this particular behaviour.

### Actions

- [ ] Reproduce it locally
- [ ] Provide a workaround
- [ ] Temporarily disable the step

**Comment by v1v** [comment]
Maybe -> [JENKINS-58476](https://issues.jenkins.io/browse/JENKINS-58476)

**Comment by v1v** [comment]
I cannot reproduce locally with a tiny monorepo example:
- https://github.com/v1v/its-gitbase/pull/9/files

**Comment by v1v** [comment]
This is a limitation with the number of nodes in the `groovy-cps`:
* https://github.com/cloudbees/groovy-cps/blob/94939d33fab9b04be76b9fbd0477b9807bf1ad32/lib/src/main/java/com/cloudbees/groovy/cps/DepthTrackingEnv.java#L8-L10

**Comment by v1v** [comment]
We won't invest anymore in the existing Jenkins implementation unless a security or a major bug, hence I'll close this issue now
